### PR TITLE
Repository cleanup

### PR DESCRIPTION
**Pull request by jvsoest**
Cleaned the repository from unnecessary code in the management_webpage folder. Also updated README.md and fixed the docker-compose in the main directory.

To load the dummy data, the script in the management_webpage/development_endpoint folder has now been changed. It now uses the main docker-compose (root of repository) as well.

### CODE REVIEW

**Comment by shashankmc** [comment]
I'm not sure if I was doing something wrong but running `docker-compose up -d` at root created an error for the `epnd_fairification_webui_1` container, specifically with the port. 
`"Error for webui: Cannot start service webui: Ports are not available, already in use."`

I was able to resolve the issue by commenting out port and address in `run.sh` under `management_webpage`, and in the `docker-compose.yml` file in the root of the repo. Unsure if I did something wrong.

**Comment by jvsoest** [comment]
> I'm not sure if I was doing something wrong but running `docker-compose up -d` at root created an error for the `epnd_fairification_webui_1` container, specifically with the port. `"Error for webui: Cannot start service webui: Ports are not available, already in use."`
> 
> I was able to resolve the issue by commenting out port and address in `run.sh` under `management_webpage`, and in the `docker-compose.yml` file in the root of the repo. Unsure if I did something wrong.

Could it be you had a service running on port 5000? I'm not sure if the issue is for port 5000 in the container, or on the host?

**Comment by shashankmc** [comment]
Yeah, sorry, my bad. Turns out that port by default is allocated to Control Center on mac (and can disable by unchecking Airplay receiver in system preferences). This is also weird considering when I made the changes I mentioned in my previous comment, the port would be accessible and everything would work.

**Comment by jvsoest** [comment]
> Yeah, sorry, my bad. Turns out that port by default is allocated to Control Center on mac (and can disable by unchecking Airplay receiver in system preferences). This is also weird considering when I made the changes I mentioned in my previous comment, the port would be accessible and everything would work.

Sounds very familiar, also spend several hours fixing that one when upgrading to macOS Monterey.....

**Pull request merged**
